# Accton Platform modules — wedge100s-only development build
#
# This branch builds ONLY the Wedge 100S-32X platform module.
# Do not merge upstream — restore all-platforms .mk for PRs.

ACCTON_WEDGE100S_32X_PLATFORM_MODULE_VERSION = 1.1

export ACCTON_WEDGE100S_32X_PLATFORM_MODULE_VERSION

ACCTON_WEDGE100S_32X_PLATFORM_MODULE = sonic-platform-accton-wedge100s-32x_$(ACCTON_WEDGE100S_32X_PLATFORM_MODULE_VERSION)_amd64.deb
$(ACCTON_WEDGE100S_32X_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-accton
$(ACCTON_WEDGE100S_32X_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(PDDF_PLATFORM_MODULE_SYM)
$(ACCTON_WEDGE100S_32X_PLATFORM_MODULE)_PLATFORM = x86_64-accton_wedge100s_32x-r0
SONIC_DPKG_DEBS += $(ACCTON_WEDGE100S_32X_PLATFORM_MODULE)
SONIC_PLATFORM += $(ACCTON_WEDGE100S_32X_PLATFORM_MODULE)
